Fix keyboard accessibility
nextcloud/notifications pull request #1236
Opened 2022-07-25 10:39 UTC by CarlSchwan

2022-07-25 10:50 UTC, nickvergessen commented on src/NotificationsApp.vue
> +		v-if="!shutdown"
Some eslints here

2022-07-25 10:51 UTC, nickvergessen commented
> HeaderMenu is taken from core/src/components and should probably be moved to nextcloud-vue

Sounds like it.

2022-07-25 13:25 UTC, CarlSchwan commented
> > HeaderMenu is taken from core/src/components and should probably be moved to nextcloud-vue
> 
> Sounds like it.

I created https://github.com/nextcloud/nextcloud-vue/pull/2886 but don't think this should be blocking for this PR (we can adapt to the newer component in another PR)

2022-07-26 08:45 UTC, nickvergessen commented
Am I doing something wrong?

Neither with notifcation nor without the content is shown to me

#### Without
![Bildschirmfoto vom 2022-07-26 10-44-01](https://user-images.githubusercontent.com/213943/180964111-6b6c9775-1325-45fa-bd63-f4bb771c4a4b.png)

### With notification
![Bildschirmfoto vom 2022-07-26 10-44-18](https://user-images.githubusercontent.com/213943/180964144-6f4d6e93-f10c-4045-bda5-86d6eb9b2e16.png)

2022-07-28 12:41 UTC, CarlSchwan commented
> Am I doing something wrong?
> 
> Neither with notifcation nor without the content is shown to me
> #### Without
> 
> ![Bildschirmfoto vom 2022-07-26 10-44-01](https://user-images.githubusercontent.com/213943/180964111-6b6c9775-1325-45fa-bd63-f4bb771c4a4b.png)
> ### With notification
> 
> ![Bildschirmfoto vom 2022-07-26 10-44-18](https://user-images.githubusercontent.com/213943/180964144-6f4d6e93-f10c-4045-bda5-86d6eb9b2e16.png)

fixed now

2022-07-29 13:54 UTC, nickvergessen requested changes

2022-07-29 13:54 UTC, nickvergessen commented on src/NotificationsApp.vue
> +		class="Notifications"
The dot is not red anymore if there is a new notification.
```suggestion
		class="notifications-button"
```

But then positions are off, so maybe most of the rules directly in `notifications-button` should be removed?

2022-07-29 15:03 UTC, nickvergessen approved these changes

2022-07-29 15:07 UTC, merged