Take theming info from initial state so it only updates once
nextcloud/notifications pull request #946
Opened 2021-04-28 07:44 UTC by nickvergessen

Fix #945 

By using the theming info from initial state directly instead of OCA.Theming, it is available immediately and doesn't create another icon request which is canceled

2021-04-28 09:07 UTC, juliushaertl approved these changes

2021-04-28 09:08 UTC, juliushaertl requested changes

2021-04-28 09:08 UTC, juliushaertl commented on src/App.vue
> +			invertedTheme2: false,
Oh just catched

```suggestion
			invertedTheme: false,
```

2021-04-28 09:13 UTC, nickvergessen commented on src/App.vue
> +			invertedTheme2: false,
ah was from a testing attempt

2021-05-04 14:57 UTC, juliushaertl approved these changes

2021-05-04 14:57 UTC, merged